plugins {
    id 'wkq.android.feature'
    id 'wkq.router'
}

android {
    namespace = 'com.wkq.test'
}

dependencies {
    implementation project(':core:core_media')
    implementation project(':core:core_network')
    implementation project(':component:component_media')
    implementation project(':component:component_web')
}
