pluginManagement {
    includeBuild("build-logic")

    repositories {
        maven { url = "https://jitpack.io" }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = "https://jitpack.io" }
        google()
        mavenCentral()
    }
}

rootProject.name = "ApplicationArchitecture"
include ':app'

// 核心层
include ':core:core_aar'
include ':core:core_base'
include ':core:core_network'
include ':core:core_ui'
include ':core:core_util'
include ':core:core_storage'
include ':core:core_data'
include ':core:core_user'
include ':core:core_media'
include ':core:core_router_annotation'
include ':core:core_router_api'
include ':core:core_router_processor'

// 可复用业务组件层
include ':component:component_web'
include ':component:component_media'
include ':component:component_live'
include ':component:component_beauty'
include ':component:component_pay'
include ':component:component_im'

// 业务功能层
include ':feature:feature_app'
include ':feature:feature_res'
include ':feature:feature_test'
