plugins {
    id 'wkq.android.component'
    id 'wkq.router'
}

android {
    namespace ='com.wkq.common'
}

dependencies {
    implementation( libs.androidx.appcompat)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.xpopup)

    implementation project(':core:core_base')
    implementation project(':core:core_user')
    implementation project(':core:core_util')
    implementation project(':component:component_media')

}
