plugins {
    id 'wkq.android.feature'
    id 'wkq.router'
}

android {
    namespace = 'com.wkq.feature.app'
}

dependencies {
    implementation project(':core:core_data')

    api('com.github.yyued:SVGAPlayer-Android:2.6.1') {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-android-extensions-runtime'
    }
}

