plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ksp)
}

android {
    namespace = "com.wkq.site.report"
    compileSdk appConfig.compileSdk

    defaultConfig {
        minSdk appConfig.minSdk
        consumerProguardFiles "consumer-rules.pro"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget = appConfig.jvmTarget
        freeCompilerArgs.add("-Xskip-metadata-version-check")
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.room.runtime
    implementation libs.androidx.room.ktx
    implementation libs.kotlinx.coroutines.android
    ksp libs.androidx.room.compiler
}
