plugins {
    id 'wkq.android.application'
}

android {
    signingConfigs {
        release {
            storeFile = file('test.jks')
            storePassword = '123456'
            keyAlias = 'test'
            keyPassword = '123456'
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.release
        }
        debug {
            signingConfig = signingConfigs.release
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def outputFile = output.outputFile
            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                def buildType = variant.buildType.name
                def versionName = variant.versionName
                def time = new Date().format("yyyyMMdd_HHmm")
                def fileName = appConfig.appNamespace + "_${buildType}_v${versionName}_${time}.apk"
                outputFileName = fileName
            }
        }
    }
}

dependencies {
    // 壳工程只显式装配启动链路需要的 feature/component。
    implementation project(':component:component_web')
    implementation project(':feature:feature_app')
    implementation project(':feature:feature_test')
}

tasks.whenTaskAdded { task ->
    if (task.name.matches(/merge.*NativeLibs/)) {
        def shouldPrintSo = project.hasProperty("printSo")

        task.doFirst {
            if (shouldPrintSo) {
                println("------- [${task.name}] start scanning so files -------")
                it.inputs.files.each { file ->
                    printSoFiles(file)
                }
                println("------- [${task.name}] end scanning so files -------")
            }
        }
    }
}

def printSoFiles(File file) {
    if (file == null || !file.exists()) return

    if (file.isDirectory()) {
        file.listFiles()?.each { printSoFiles(it) }
    } else if (file.name.endsWith(".so")) {
        println("Found .so: ${file.absolutePath}")
    }
}
