plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = appConfig.appNamespace
    compileSdk appConfig.compileSdk
    def enableReleaseMinify = providers.gradleProperty("enableReleaseMinify")
            .map { it.toBoolean() }
            .getOrElse(false)

    defaultConfig {
        applicationId appConfig.appNamespace
        minSdk appConfig.minSdk
        targetSdk appConfig.targetSdk
        versionCode appConfig.versionCode
        versionName appConfig.versionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile = file('test.jks')
            storePassword = '123456'
            keyAlias = 'test'
            keyPassword = '123456'
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.release
            minifyEnabled enableReleaseMinify
            shrinkResources enableReleaseMinify
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig = signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def outputFile = output.outputFile
            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                def buildType = variant.buildType.name
                def versionName = variant.versionName
                def time = new Date().format("yyyyMMdd_HHmm")
                def fileName = appConfig.appNamespace + "_${buildType}_v${versionName}_${time}.apk"
                outputFileName = fileName
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = appConfig.jvmTarget
    }
}

dependencies {
    implementation project(':component:component_web')
    implementation project(':feature:feature_app')
    implementation project(':feature:feature_test')

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.constraintlayout

    implementation project(':core:core_base')
    implementation project(':core:core_util')
    implementation project(':core:core_storage')
    implementation project(':core:core_media')
    implementation project(':core:core_ui')
    implementation project(':core:core_network')
    implementation project(':core:core_router_api')
    implementation project(':core:core_user')

    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}

tasks.whenTaskAdded { task ->
    if (task.name.matches(/merge.*NativeLibs/)) {
        def shouldPrintSo = project.hasProperty("printSo")

        task.doFirst {
            if (shouldPrintSo) {
                println("------- [${task.name}] start scanning so files -------")
                it.inputs.files.each { file ->
                    printSoFiles(file)
                }
                println("------- [${task.name}] end scanning so files -------")
            }
        }
    }
}

def printSoFiles(File file) {
    if (file == null || !file.exists()) return

    if (file.isDirectory()) {
        file.listFiles()?.each { printSoFiles(it) }
    } else if (file.name.endsWith(".so")) {
        println("Found .so: ${file.absolutePath}")
    }
}
