import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    // 依赖注解模块
    implementation project(":router:router_annotation")

    // KSP
    implementation libs.ksp.api

    // 代码生成
    implementation libs.kotlinpoet
    implementation libs.kotlinpoet.ksp
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}