plugins {
    id 'java-gradle-plugin'
}

gradlePlugin {
    plugins {
        androidLibrary {
            id = 'wkq.android.library'
            implementationClass = 'com.wkq.buildlogic.AndroidLibraryConventionPlugin'
        }
        androidApplication {
            id = 'wkq.android.application'
            implementationClass = 'com.wkq.buildlogic.AndroidApplicationConventionPlugin'
        }
        androidFeature {
            id = 'wkq.android.feature'
            implementationClass = 'com.wkq.buildlogic.AndroidFeatureConventionPlugin'
        }
        androidComponent {
            id = 'wkq.android.component'
            implementationClass = 'com.wkq.buildlogic.AndroidComponentConventionPlugin'
        }
        router {
            id = 'wkq.router'
            implementationClass = 'com.wkq.buildlogic.RouterConventionPlugin'
        }
        architectureCheck {
            id = 'wkq.architecture-check'
            implementationClass = 'com.wkq.buildlogic.ArchitectureCheckPlugin'
        }
    }
}
