plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = 'com.wkq.media'
    compileSdk appConfig.compileSdk

    defaultConfig {
        minSdk appConfig.minSdk
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget = appConfig.jvmTarget
        freeCompilerArgs.addAll(["-Xskip-metadata-version-check"])
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation project(':core:core_util')

    api libs.coil
    api libs.coil3.coil.gif
    implementation libs.coil.network.okhttp
    implementation libs.luban
}
