plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.wkq.camera"
    compileSdk appConfig.compileSdk

    defaultConfig {
        minSdk appConfig.minSdk
        consumerProguardFiles "consumer-rules.pro"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }
}

kotlin {
    compilerOptions {
        jvmTarget = appConfig.jvmTarget
        freeCompilerArgs.add("-Xskip-metadata-version-check")
    }
}

dependencies {
    implementation project(":core:core_util")
    implementation project(":core:core_location")
    implementation libs.androidx.core.ktx
    implementation libs.androidx.camera.camera2
    implementation libs.androidx.camera.lifecycle
    implementation libs.androidx.camera.view
    implementation libs.androidx.exifinterface
    implementation libs.kotlinx.coroutines.android
}
